---
title: "report"
output: pdf_document
date: "2025-01-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
setwd("C:/Users/Stefa/Documents/1-Stefano/1-Medica/1-Report")
dati<-read.table("mussels2.txt",sep=",",header = T)
attach(dati)
library(ggplot2)
library(e1071)
library(tseries)
```
ac = Stepping stones to Alabama-Coosa 
ap = Stepping stones to Apalachicola
sv = Stepping stones to Savannah
sl = Stepping stones to St. Lawrence
sr = Solid Residue   
hy = Hydronium   



# analisi esplorative
## univariate

```{r}
#specie
summary(specie)
sd(specie)
IQR(specie)
# Calcola la skewness
(skewness_value <- skewness(specie))
jarque.bera.test(specie)

ggplot(data=dati, aes(x=factor(0),y=specie,fill=factor(0)))+
  geom_violin(trim=F)+
  geom_boxplot(width=0.2,fill="white")+
  scale_fill_manual(values="cadetblue3",
                    labels="boh")+
  labs(x="", y="Species")+
  theme(legend.position = "none")

#area
summary(area)
sd(area)
IQR(area)
# Calcola la skewness
(skewness_value <- skewness(area))
jarque.bera.test(area)

ggplot(data=dati, aes(x=factor(0),y=area,fill=factor(0)))+
  geom_violin(trim=F)+
  geom_boxplot(width=0.2,fill="white")+
  scale_fill_manual(values="cadetblue3",
                    labels="boh")+
  labs(x="", y="Area")+
  theme(legend.position = "none")

#area ma mettiamo il log.area
#summary(area)
#sd(area)
#IQR(area)
#boxplot(area)
#ggplot(data=dati, aes(x=factor(0),y=area,fill=factor(0)))+
  #geom_violin(trim=F)+
  #geom_boxplot(width=0.2,fill="white")+
  #scale_fill_manual(values="cadetblue3",
                    #labels="boh")+
  #labs(x="", y="Area")+
  #theme(legend.position = "none")

#Stepping stones to Alabama-Coosa 
summary(ac)
sd(ac)
IQR(ac)
(skewness_value <- skewness(ac))
jarque.bera.test(ac)
ggplot(data=dati, aes(x=factor(0),y=ac,fill=factor(0)))+
  geom_violin(trim=F)+
  geom_boxplot(width=0.2,fill="white")+
  scale_fill_manual(values="cadetblue3",
                    labels="boh")+
  labs(x="", y="Stepping stones to Alabama-Coosa")+
  theme(legend.position = "none")

#Stepping stones to Apalachicola
summary(ap)
sd(ap)
IQR(ap)
(skewness_value <- skewness(ap))
jarque.bera.test(ap)
ggplot(data=dati, aes(x=factor(0),y=ap,fill=factor(0)))+
  geom_violin(trim=F)+
  geom_boxplot(width=0.2,fill="white")+
  scale_fill_manual(values="cadetblue3",
                    labels="boh")+
  labs(x="", y="Stepping stones to Apalachicola")+
  theme(legend.position = "none")

#Stepping stones to Savannah
summary(sv)
sd(sv)
IQR(sv)
(skewness_value <- skewness(sv))
jarque.bera.test(sv)
ggplot(data=dati, aes(x=factor(0),y=sv,fill=factor(0)))+
  geom_violin(trim=F)+
  geom_boxplot(width=0.2,fill="white")+
  scale_fill_manual(values="cadetblue3",
                    labels="boh")+
  labs(x="", y="Stepping stones to Savannah")+
  theme(legend.position = "none")

#Stepping stones to St. Lawrence 
summary(sl)
sd(sl)
IQR(sl)
(skewness_value <- skewness(sl))
jarque.bera.test(sl)
ggplot(data=dati, aes(x=factor(0),y=sl,fill=factor(0)))+
  geom_violin(trim=F)+
  geom_boxplot(width=0.2,fill="white")+
  scale_fill_manual(values="cadetblue3",
                    labels="boh")+
  labs(x="", y="Stepping stones to St. Lawrence")+
  theme(legend.position = "none")

#concentrazione di nitrato
summary(nitrate)
sd(nitrate)
IQR(nitrate)
(skewness_value <- skewness(nitrate))
jarque.bera.test(nitrate)
ggplot(data=dati, aes(x=factor(0),y=nitrate,fill=factor(0)))+
  geom_violin(trim=F)+
  geom_boxplot(width=0.2,fill="white")+
  scale_fill_manual(values="cadetblue3",
                    labels="boh")+
  labs(x="", y="Nitrate concentration")+
  theme(legend.position = "none")

#residui solidi
summary(sr)
sd(sr)
IQR(sr)
(skewness_value <- skewness(sr))
jarque.bera.test(sr)
ggplot(data=dati, aes(x=factor(0),y=sr,fill=factor(0)))+
  geom_violin(trim=F)+
  geom_boxplot(width=0.2,fill="white")+
  scale_fill_manual(values="cadetblue3",
                    labels="boh")+
  labs(x="", y="Solid residue")+
  theme(legend.position = "none")

#idronio
summary(hy)
sd(hy)
IQR(hy)
(skewness_value <- skewness(hy))
jarque.bera.test(hy)
ggplot(data=dati, aes(x=factor(0),y=hy,fill=factor(0)))+
  geom_violin(trim=F)+
  geom_boxplot(width=0.2,fill="white")+
  scale_fill_manual(values="cadetblue3",
                    labels="boh")+
  labs(x="", y="Hydronium concentration")+
  theme(legend.position = "none")

#logaritmo dell'area è simmetrico e non ci sono valori anomali
summary(ln.area)
sd(ln.area)
IQR(ln.area)
(skewness_value <- skewness(ln.area))
jarque.bera.test(ln.area)
ggplot(data=dati, aes(x=factor(0),y=ln.area,fill=factor(0)))+
  geom_violin(trim=F)+
  geom_boxplot(width=0.2,fill="white")+
  scale_fill_manual(values="cadetblue3",
                    labels="boh")+
  labs(x="", y="Logarithm of the area")+
  theme(legend.position = "none")
```

## bivariate
```{r}
library(car)
scatterplotMatrix(dati[,2:11])
cor(dati[,2:11],method = "spearman")
variable_names = c("specie","area","ac","ap","sv","sl","nitrate","sr","hy","ln.area") 
#per vedere quali correlazioni sono significative
sign <- matrix(NA, nrow = 10, ncol = 10)
for (i in 1:10) {
  for (j in 1:10) {
    if (i != j) { 
      h <- cor.test(dati[, i + 1], dati[, j + 1], method = "spearman") 
      if (h$p.value < 0.05) {
        sign[i, j] <- 1
      } else {
        sign[i, j] <- 0
      }
    }
  }
}
sign

rownames(sign) <- variable_names
colnames(sign) <- variable_names

# stampa la matrice sign con i nomi delle variabili sugli assi
print(sign)

cor.test(dati[, 9], dati[, 3], method = "spearman") 
#vanno messi i test per verificare se la correlazione è significativa

#area-specie 
#ggplot(dati, aes(x = area, y = specie)) +
#  geom_point() +
# geom_smooth(method = "lm", se = TRUE) +
#  labs(x = "Area", y = "Number of Species")
#cor.test(area,specie,method = "spearman")

#ac-specie (non significativo)
ggplot(dati, aes(x = ac, y = specie)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Stepping Stones to Alabama-Coosa", y = "Number of Species")
cor.test(ac,specie, method = "spearman")

#ap-specie (non significativo)
ggplot(dati, aes(x = ap, y = specie)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Stepping Stones to Apalachicola", y = "Number of Species")
cor.test(ap,specie, method = "spearman")

#sv-specie (non significativo)
ggplot(dati, aes(x = sv, y = specie)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Stepping Stones to Savannah", y = "Number of Species")
cor.test(sv,specie, method = "spearman")

#sl-speice (non significativo)
ggplot(dati, aes(x = sl, y = specie)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Stepping Stones to St. Lawrence", y = "Number of Species")
cor.test(sl,specie, method = "spearman")

#nitrate -specie (non significativo)
ggplot(dati, aes(x = nitrate, y = specie)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Nitrate Concentration", y = "Number of Species")
cor.test(nitrate,specie, method = "spearman")

#sr-specie (non significativo)
ggplot(dati, aes(x = sr, y = specie)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Solid Residue", y = "Number of Species")
cor.test(sr,specie,method = "spearman")

#hy-specie 
ggplot(dati, aes(x = hy, y = specie)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Hydronium concentration", y = "Number of Species")
cor.test(hy,specie,method = "spearman")

#ln.area-specie (significativo)
ggplot(dati, aes(x = ln.area, y = specie)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Logarithm of the area", y = "Number of Species")
cor.test(ln.area,specie, method = "spearman")

#####################################################################################

#ap-ac (significativo)
ggplot(dati, aes(x = ap, y = ac)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Stepping Stones to Apalachicola", y = "Stepping Stones to Alabama-Coosa")
cor.test(ap,ac, method = "spearman")

#sv-ac (significativo)
ggplot(dati, aes(x = sv, y = ac)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Stepping Stones to Savannah", y = "Stepping Stones to Alabama-Coosa")
cor.test(sv,ac, method = "spearman")

#sl-ac (significativo)
ggplot(dati, aes(x = sl, y = ac)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Stepping Stones to St. Lawrence", y = "Stepping Stones to Alabama-Coosa")
cor.test(sl,ac, method = "spearman")

#nitrate-ac (significativo)
ggplot(dati, aes(x = nitrate, y = ac)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Nitrate Concentration", y = "Stepping Stones to Alabama-Coosa")
cor.test(nitrate,ac, method = "spearman")

#sr-ac (non significativo)
ggplot(dati, aes(x = sr, y = ac)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Solid Residue", y = "Stepping Stones to Alabama-Coosa")
cor.test(sr,ac, method = "spearman")

#hy-ac  (significativo)
ggplot(dati, aes(x = hy, y = ac)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Hydronium concentration", y = "Stepping Stones to Alabama-Coosa")
cor.test(hy,ac,method = "spearman")

#ln.area-ac (non significativo)
ggplot(dati, aes(x = ln.area, y = ac)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Logarithm of the area", y = "Stepping Stones to Alabama-Coosa")
cor.test(ln.area,ac, method = "spearman")

####################################################################################

#sv-ap (significativo)
ggplot(dati, aes(x = sv, y = ap)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Stepping Stones to Savannah", y = "Stepping Stones to Apalachicola")
cor.test(sv,ap, method = "spearman")

#sl-ap (significativo)
ggplot(dati, aes(x = sl, y = ap)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Stepping Stones to St. Lawrence", y = "Stepping Stones to Apalachicola")
cor.test(sl,ap, method = "spearman")

#nitrate-ap (significativo)
ggplot(dati, aes(x = nitrate, y = ap)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Nitrate Concentration", y = "Stepping Stones to Apalachicola")
cor.test(nitrate,ap, method = "spearman")

#sr-ap (non significativo)
ggplot(dati, aes(x = sr, y = ap)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Solid Residue", y = "Stepping Stones to Apalachicola")
cor.test(sr,ap, method = "spearman")

#hy-ap  (significativo)
ggplot(dati, aes(x = hy, y = ap)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Hydronium concentration", y = "Stepping Stones to Apalachicola")
cor.test(hy,ap,method = "spearman")

#ln.area-ap (non significativo)
ggplot(dati, aes(x = ln.area, y = ap)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Logarithm of the area", y = "Stepping Stones to Apalachicola")
cor.test(ln.area,ap, method = "spearman")

####################################################################################

#sl-sv (significativo)
ggplot(dati, aes(x = sl, y = sv)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Stepping Stones to St. Lawrence", y = "Stepping Stones to Savannah")
cor.test(sl,sv, method = "spearman")

#nitrate-sv (significativo)
ggplot(dati, aes(x = nitrate, y = sv)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Nitrate Concentration", y = "Stepping Stones to Savannah")
cor.test(nitrate,sv, method = "spearman")

#sr-sv (non significativo)
ggplot(dati, aes(x = sr, y = sv)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Solid Residue", y = "Stepping Stones to Savannah")
cor.test(sr,sv, method = "spearman")

#hy-sv  (non significativo)
ggplot(dati, aes(x = hy, y = sv)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Hydronium concentration", y = "Stepping Stones to Savannah")
cor.test(hy,sv,method = "spearman")

#ln.area-sv (non significativo)
ggplot(dati, aes(x = ln.area, y = sv)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Logarithm of the area", y = "Stepping Stones to Savannah")
cor.test(ln.area,sv, method = "spearman")

####################################################################################

#nitrate-sl (significativo)
ggplot(dati, aes(x = nitrate, y = sl)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Nitrate Concentration", y = "Stepping Stones to St. Lawrence")
cor.test(nitrate,sl, method = "spearman")

#sr-sl (non significativo)
ggplot(dati, aes(x = sr, y = sl)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Solid Residue", y = "Stepping Stones to St. Lawrence")
cor.test(sr,sl, method = "spearman")

#hy-sl  (significativo)
ggplot(dati, aes(x = hy, y = sl)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Hydronium concentration", y = "Stepping Stones to St. Lawrence")
cor.test(hy,sl,method = "spearman")

#ln.area-sl (non significativo)
ggplot(dati, aes(x = ln.area, y = sl)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Logarithm of the area", y = "Stepping Stones to St. Lawrence")
cor.test(ln.area,sl, method = "spearman")

####################################################################################

#sr-nitrate (significativo)
ggplot(dati, aes(x = sr, y = nitrate)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Solid Residue", y = "Nitrate Concentration")
cor.test(sr,nitrate, method = "spearman")

#hy-nitrate  (non significativo)
ggplot(dati, aes(x = hy, y = nitrate)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Hydronium concentration", y = "Nitrate Concentration")
cor.test(hy,nitrate,method = "spearman")

#ln.area-nitrate (non significativo)
ggplot(dati, aes(x = ln.area, y = nitrate)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Logarithm of the area", y = "Nitrate Concentration")
cor.test(ln.area,nitrate, method = "spearman")

####################################################################################

#hy-sr  (significativo)
ggplot(dati, aes(x = hy, y = sr)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Hydronium concentration", y = "Solid Residue")
cor.test(hy,sr,method = "spearman")

#ln.area-sr (non significativo)
ggplot(dati, aes(x = ln.area, y = sr)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Logarithm of the area", y = "Solid Residue")
cor.test(ln.area,sr, method = "spearman")

####################################################################################

#ln.area-hy (non significativo)
ggplot(dati, aes(x = ln.area, y = hy)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Logarithm of the area", y = "Hydronium Concentration")
cor.test(ln.area,hy, method = "spearman")

####################################################################################

```




# modello lineare

```{r}
m1<-lm(specie~ln.area+ac+ap+sv+sl+nitrate+sr+hy)
summary(m1)
drop1(m1,test="F")
m2<-lm(specie~ln.area+ap+sv+sl+nitrate+sr+hy)
summary(m2)
m3<-lm(specie~ln.area+ap+sv+nitrate+sr+hy)
summary(m3)
m4<-lm(specie~ln.area+ap+nitrate+sr+hy)
summary(m4)
m5<-lm(specie~ln.area+ap+sr+hy)
summary(m5)
add1(m5,.~+(.)^2,test="F")
m6<-lm(specie~ln.area+ap+sr+hy+ap:hy)
summary(m6)
add1(m6,.~+(.)^2,test="F")
drop1(m6,test="F")
#significativo solo log(area), Stepping stones to Apalachicola, residui solidi, Hydronium e interazione tra Stepping stones to Apalachicola e Hydronium

AIC(m6) 
AIC(m5)

#modello con interazione
#modello senza interazione
res<-rstandard(m5)
shapiro.test(res)#normalit dubbia
ggplot(data = data.frame(sample=res), aes(sample = sample)) +
  stat_qq() +                   
  stat_qq_line(color = "red") +  
  labs(x = "Theorical quantiles", y = "Sample quantiles")

ggplot(dati, aes(x = fitted(m5), y = res)) +
  geom_point(color = "blue", size = 2) +  
  labs(x = "Estimated values",y = "Model residuals") #omoschedasticità sembra ok

ggplot(dati, aes(x = specie, y = fitted(m5))) +
  geom_point(color = "blue", size = 2) +  
  labs(x = "Species",y = "Estimated values") +
  geom_abline(intercept = 0, slope = 1, color = "red")
cor(fitted(m5),specie)


#residui studentizzati
res.conint<-rstandard(m6)
shapiro.test(res.conint)#normalità ok
ggplot(data = data.frame(sample=res.conint), aes(sample = sample)) +
  stat_qq() +                   
  stat_qq_line(color = "red") +  
  labs(x = "Theorical quantiles", y = "Sample quantiles")

ggplot(dati, aes(x = fitted(m6), y = res.conint)) +
  geom_point(color = "blue", size = 2) +  
  labs(x = "Estimated values",y = "Model residuals")
#omoschedasticità sembra dubbia

ggplot(dati, aes(x = specie, y = fitted(m6))) +
  geom_point(color = "blue", size = 2) +  
  labs(x = "Species",y = "Estimated values") +
  geom_abline(intercept = 0, slope = 1, color = "red")
cor(fitted(m6),specie)#correlazione migliore

AIC(m5)
AIC(m6)#aic preferibile
```

# modello di poisson
```{r}
m7<-glm(specie~ln.area+ac+ap+sv+sl+nitrate+sr+hy,family = poisson)
summary(m7)
m8<-glm(specie~ln.area+ap+sv+sl+nitrate+sr+hy,family = poisson)
summary(m8)
m9<-glm(specie~ln.area+ap+sv+nitrate+sr+hy,family = poisson)
summary(m9)
m10<-glm(specie~ln.area+ap+nitrate+sr+hy,family = poisson)
summary(m10)
m11<-glm(specie~ln.area+ap+sr+hy,family = poisson)
summary(m11)
add1(m11,.~+(.)^2,test="Chisq")
m12<-glm(specie~ln.area+ap+sr+hy+ap:hy,family = poisson)
summary(m12)
#significativo solo log(area), Stepping stones to Apalachicola, residui solidi, Hydronium e interazione tra Stepping stones to Apalachicola e Hydronium

#validazione modello senza interazione
#test modello nullo (da verificare fatto da chatgbt)
delta_deviance <- m11$null.deviance - m11$deviance
delta_df <- m11$df.null- m11$df.residual 
p_value <- pchisq(delta_deviance, df = delta_df, lower.tail = FALSE)
p_value

#normalità residui 
res1<-residuals.glm(m11)
shapiro.test(res1)
ggplot(data = data.frame(sample=res1), aes(sample = sample)) +
  stat_qq() +                   
  stat_qq_line(color = "red") +  
  labs(x = "Theorical quantiles", y = "Sample quantiles")

#omoschedasticità
ggplot(dati, aes(x = fitted(m11), y = res1)) +
  geom_point(color = "blue", size = 2) +  
  labs(x = "Estimated values",y = "Model residuals")
#plot(res1,fitted(m11,type="response"))
#plot(specie,fitted(m11,type="response"))
#abline(0,1)
ggplot(dati, aes(x = specie, y = fitted(m11))) +
  geom_point(color = "blue", size = 2) +  
  labs(x = "Species",y = "Estimated values") +
  geom_abline(intercept = 0, slope = 1, color = "red")
cor(specie,fitted(m11,type="response"))

#non c'è sovradispersione
X2<-sum((residuals(m11, type="pearson"))^2)
1-pchisq(X2,m11$df.residual)


#modello con interazione
#test modello nullo
delta_deviance1 <- m12$null.deviance - m12$deviance
delta_df1 <- m12$df.null- m12$df.residual 
p_value <- pchisq(delta_deviance1, df = delta_df1, lower.tail = FALSE)
p_value

#normalità residui modello senza interazioni
res1.conint<-residuals.glm(m12)
shapiro.test(res1.conint)
ggplot(data = data.frame(sample=res1.conint), aes(sample = sample)) +
  stat_qq() +                   
  stat_qq_line(color = "red") +  
  labs(x = "Theorical quantiles", y = "Sample quantiles")

ggplot(dati, aes(x = fitted(m12), y = res1.conint)) +
  geom_point(color = "blue", size = 2) +  
  labs(x = "Estimated values",y = "Model residuals")

ggplot(dati, aes(x = specie, y = fitted(m12))) +
  geom_point(color = "blue", size = 2) +  
  labs(x = "Species",y = "Estimated values") +
  geom_abline(intercept = 0, slope = 1, color = "red")
cor(specie,fitted(m12,type="response"))

#non c'è sovradispersione
X2<-sum((residuals(m12, type="pearson"))^2)
1-pchisq(X2,m12$df.residual)

AIC(m11)
AIC(m12)
 
```

## confronto AIC
```{r}
#modelli senza interazione
AIC(m5)
AIC(m11)
#modelli con interazione
AIC(m6)
AIC(m12)
```




## altre funzioni legame
```{r}
m13<-glm(specie~ln.area+ac+nitrate+sr+hy,family = poisson(link="identity"))
summary(m13)

m14<-glm(specie~ln.area+ac+nitrate+sr+hy+ln.area:nitrate,family = poisson(link="identity"))
summary(m14)


m15<-glm(specie~ln.area+ap+nitrate+sr+hy,family = poisson(link="sqrt"))
summary(m15)

m16<-glm(specie~ln.area+ap+nitrate+sr+hy+ln.area:nitrate,family = poisson(link="sqrt"))
summary(m16)

AIC(m13)
AIC(m15)
AIC(m11)#migliore

AIC(m12)#migliore
AIC(m14)
AIC(m16)
```




```{r}
library(cluster)
library(factoextra)

# PCA
pca_data <- dati[, c("ln.area", "nitrate", "hy", "sr")]
pca_result <- prcomp(pca_data, scale = TRUE)
fviz_pca_biplot(pca_result, repel = TRUE)

# Clustering
#metodo 1
km1<-kmeans(pca_data,centers=3)
explainde.var<-rep(NA,10)
for(i in 1:10){
  km<-kmeans(pca_data,centers=i)
  explainde.var[i]<-km$betweenss/km$totss
}
plot(c(1:10),explainde.var,type="l")
library(ggfortify)
autoplot(km1,data=pca_data,frame=T)

#metodo 2
dist_matrix <- dist(pca_data)
cluster_result <- hclust(dist_matrix, method = "complete")
plot(cluster_result)

```

